### PR TITLE
fix: updated GraphQL queries to V2

### LINKED ISSUE #46: Update GraphQL queries to Project V2
`ProjectNext` query is deprecated and soon will stop working.

We need to update to use `ProjectV2`.

[Example call](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-api-to-manage-projects#using-variables)

[Documentation](https://docs.github.com/en/graphql/reference/objects#projectv2)

### PR DESCRIPTION
**Pull request by Bullrich**
Updated GraphQL queries to support version 2 as `ProjectNext` has been deprecated.

Moved all the queries to be stored in a exported variables so they can be accessed from outside.

Created unit tests which validates the schemas using `@octokit/graphql-schema` which contains the latest schemas. 

Modified dependabot to keep the `@octokit/graphql-schema` dependency at its latest.

This commit closes #46.

### CODE REVIEW

File: src/github/projectKit.ts [hunk 1]
```diff
@@ -2,32 +2,60 @@ import { graphql } from "@octokit/graphql";
...
-          id: string;
-          name: string;
-          settings?: string | null;
-        }[];
-      };
-    };
-  };
+type NodeData = { id: string; title: string };
+
+export const PROJECT_V2_QUERY: string = `
```
Comment (mutantcornholio) [inline src/github/projectKit.ts:7]: Any objections to using [graphql-tag](https://www.npmjs.com/package/graphql-tag) on the queries? It'll bring syntax highlighting at least

File: .github/dependabot.yml [hunk 2]
```diff
@@ -10,3 +10,9 @@ updates:
         # Ignore version upgrades.
         # Security updates are nevertheless. unaffected by this setting and will continue to work.
         update-types: ["version-update:semver-patch", "version-update:semver-minor", "version-update:semver-major"]
+  - package-ecosystem: "npm"
+    directory: "/"
+    schedule:
+      interval: "monthly"
```
Comment (rzadp) [inline .github/dependabot.yml:16]: Is it not too rare? Checking more often doesn't cost us anything?

Comment (Bullrich) [reply .github/dependabot.yml:16]: They sometimes do multi releases in the same day, I don’t want dependabot to make a million PRs per month and a monthly rate sounds good to keep an eye on it without it being too verbose. Wdyt?

File: src/github/projectKit.ts (hunk 1 above)
Comment (Bullrich) [reply src/github/projectKit.ts:7]: OMG I think this is exactly what I need. Let me try it out!

Comment (mordamax) [reply src/github/projectKit.ts:7]: there's also one method, which gives you autocomplete of GQL 
Implemented in this project: https://github.com/paritytech/roadmap/blob/main/getProjects.graphql

But this is pain in ass to set this up :)

Comment (Bullrich) [reply src/github/projectKit.ts:7]: Yeah, we just discussed to skip it, we already have all the queries written down and [the tests for the queries](https://github.com/paritytech/github-issue-sync/pull/50/files#diff-166bb1d8f11fa6c00b35cd25d25a496c116826c7c4ec40f7de96a2797154c88a) are already validating that the queries can compile and are using the correct types.

If they are modified and become invalid the tests will throw errors like:
- `GraphQLError: Syntax Error: Expected Name, found <EOF>.`
- `GraphQLError: Cannot query field "titles" on type "ProjectV2". Did you mean "title", "fields", or "items"?`

Comment (mordamax) [reply src/github/projectKit.ts:7]: sounds good
